name: Build and Publish Docs on Dispatch

on:
  workflow_dispatch:

jobs:
  docs:
    uses: scikit-package/release-scripts/.github/workflows/_release-docs.yml@{{ VERSION/v0 }}
    with:
      project: {{ PROJECT/PROJECT_NAME }}
      c_extension: {{ C_EXTENSION/false }}
      headless: {{ HEADLESS/false }}
